"""Bzlmod extension. Same shape as rules_pg / rules_temporal / rules_kind /
rules_playwright (the version tag class). v0.1 has no `system` mode — Capsule
is an in-cluster operator, not a host CLI.
"""

load("//private:repositories.bzl", "capsule_version_repository")

_version_tag = tag_class(attrs = {
    "name": attr.string(default = "capsule"),
    "version": attr.string(mandatory = True),
})

def _impl(mctx):
    # Only honor `version` tags from the root module. Without this guard,
    # both rules_capsule (when consumed as a dep) and the consumer would each
    # emit a `@capsule` repo with the same `name`, and Bazel collides them:
    # "A repo named capsule is already generated by this module extension".
    # The library's own MODULE.bazel still needs `capsule.version()` so its
    # in-tree smoke test can build, but that only fires when rules_capsule
    # itself is the root.
    for mod in mctx.modules:
        if not mod.is_root:
            continue
        for tag in mod.tags.version:
            capsule_version_repository(
                name = tag.name,
                version = tag.version,
            )

capsule = module_extension(
    implementation = _impl,
    tag_classes = {"version": _version_tag},
)
