"""Generated by tools/render_capsule.sh + tools/update_checksums.sh — do not edit by hand.

Schema:

    CAPSULE_VERSIONS = {
        "<capsule-version>": {
            "manifest_sha256": "<sha256 of the rendered Capsule manifest>",
        },
    }

    CERT_MANAGER = {
        "version": "<cert-manager-version>",
        "url": "<cert-manager.yaml URL>",
        "sha256": "<sha256>",
    }

The Capsule manifest itself is pre-rendered (`helm template …`) by a maintainer
and committed under `private/manifests/capsule-<ver>.yaml`. We sha256-check it
at build time so a tampered checkout fails loudly.

cert-manager is pinned for the in-tree smoke test only — it is not part of
the public `capsule_install` contract. See DESIGN.md decision #6.
"""

CAPSULE_VERSIONS = {
    "0.10.4": {
        "manifest_sha256": "f6ee579854a0558d04e752302954fa6108b6e89e7fb659f2b13bd78c30050b57",
    },
}

CERT_MANAGER = {
    "version": "1.18.3",
    "url": "https://github.com/cert-manager/cert-manager/releases/download/v1.18.3/cert-manager.yaml",
    "sha256": "f12a78d93d77e1eb9dea0b6d7c931b26da287492fcdf0eb58620142883d4675a",
}

PLATFORMS = {
    "darwin_amd64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx", "@platforms//cpu:arm64"],
    "linux_amd64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],
}
