"""Generated by tools/render_capsule.sh + tools/update_checksums.sh — do not edit by hand.

Schema:

    CAPSULE_VERSIONS = {
        "<capsule-version>": {
            "manifest_sha256": "<sha256 of the rendered Capsule manifest>",
            "chart_url":       "<URL of capsule-<ver>.tgz>",
            "chart_sha256":    "<sha256 of the chart .tgz>",
        },
    }

    CERT_MANAGER = {
        "version": "<cert-manager-version>",
        "url": "<cert-manager.yaml URL>",
        "sha256": "<sha256>",
    }

The Capsule manifest itself is pre-rendered (`helm template …`) by a maintainer
and committed under `private/manifests/capsule-<ver>.yaml`. We sha256-check it
at build time so a tampered checkout fails loudly.

The chart .tgz is used by the maintainer-side render flow only
(`bazel run //tools:render_writeback -- <version>`). Consumers don't download
it; they consume the committed pre-rendered manifest.

cert-manager is pinned for the in-tree smoke test only — it is not part of
the public `capsule_install` contract. See DESIGN.md decision #6.
"""

CAPSULE_VERSIONS = {
    "0.10.4": {
        "manifest_sha256": "b8978571f4233ef74b63e245eb91f29b1c55148a5dbe96b14073d6773872ccc5",
        "chart_url":       "https://projectcapsule.github.io/charts/capsule-0.10.4.tgz",
        "chart_sha256":    "666534a2c377259908a1870057aa8a3f9c080e3cca98ad56d2c0068680e38fc2",
    },
}

CERT_MANAGER = {
    "version": "1.18.3",
    "url": "https://github.com/cert-manager/cert-manager/releases/download/v1.18.3/cert-manager.yaml",
    "sha256": "f12a78d93d77e1eb9dea0b6d7c931b26da287492fcdf0eb58620142883d4675a",
}

PLATFORMS = {
    "darwin_amd64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx", "@platforms//cpu:arm64"],
    "linux_amd64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],
}
